<a href="https://colab.research.google.com/github/Tlezcano/tlezcano/blob/main/Python_2LEZCANO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Big Data

# pandas data frame

In [1]:
import pandas as pd
from google.colab import files

In [2]:
d_star_wars = pd.read_csv(filepath_or_buffer="https://raw.githubusercontent.com/fpineyro/homework-0/master/starwars.csv", sep=',')
d_star_wars

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,species
0,Luke Skywalker,172.0,77,blond,fair,blue,19BBY,male,Tatooine,Human
1,C-3PO,167.0,75,NaN,gold,yellow,112BBY,NaN,Tatooine,Droid
2,R2-D2,96.0,32,NaN,"white, blue",red,33BBY,NaN,Naboo,Droid
3,Darth Vader,202.0,136,none,white,yellow,41.9BBY,male,Tatooine,Human
4,Leia Organa,150.0,49,brown,light,brown,19BBY,female,Alderaan,Human
...,...,...,...,...,...,...,...,...,...,...
82,Rey,NaN,NaN,brown,light,hazel,NaN,female,NaN,Human
83,Poe Dameron,NaN,NaN,brown,light,brown,NaN,male,NaN,Human
84,BB8,NaN,NaN,none,none,black,NaN,none,NaN,Droid
85,Captain Phasma,NaN,NaN,NaN,NaN,NaN,NaN,female,NaN,NaN
86,Padmé Amidala,165.0,45,brown,light,brown,46BBY,female,Naboo,Human

In [3]:
#Mostrar todas las columas del dataframa
d_star_wars.columns

Index(['name', 'height', 'mass', 'hair_color', 'skin_color', 'eye_color',
       'birth_year', 'gender', 'homeworld', 'species'],
      dtype='object')

### 1) ¿Cómo eliminar columnas?

In [4]:
# Una columna
d_star_wars.drop(columns='name')

,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,species
0,172.0,77,blond,fair,blue,19BBY,male,Tatooine,Human
1,167.0,75,NaN,gold,yellow,112BBY,NaN,Tatooine,Droid
2,96.0,32,NaN,"white, blue",red,33BBY,NaN,Naboo,Droid
3,202.0,136,none,white,yellow,41.9BBY,male,Tatooine,Human
4,150.0,49,brown,light,brown,19BBY,female,Alderaan,Human
...,...,...,...,...,...,...,...,...,...
82,NaN,NaN,brown,light,hazel,NaN,female,NaN,Human
83,NaN,NaN,brown,light,brown,NaN,male,NaN,Human
84,NaN,NaN,none,none,black,NaN,none,NaN,Droid
85,NaN,NaN,NaN,NaN,NaN,NaN,female,NaN,NaN
86,165.0,45,brown,light,brown,46BBY,female,Naboo,Human

In [5]:
# Eliminar N columnas
d_star_wars.drop(columns=['name', 'height'])

   mass hair_color   skin_color eye_color birth_year  gender homeworld species
0    77      blond         fair      blue      19BBY    male  Tatooine   Human
1    75        NaN         gold    yellow     112BBY     NaN  Tatooine   Droid
2    32        NaN  white, blue       red      33BBY     NaN     Naboo   Droid
3   136       none        white    yellow    41.9BBY    male  Tatooine   Human
4    49      brown        light     brown      19BBY  female  Alderaan   Human
..  ...        ...          ...       ...        ...     ...       ...     ...
82  NaN      brown        light     hazel        NaN  female       NaN   Human
83  NaN      brown        light     brown        NaN    male       NaN   Human
84  NaN       none         none     black        NaN    none       NaN   Droid
85  NaN        NaN          NaN       NaN        NaN  female       NaN     NaN
86   45      brown        light     brown      46BBY  female     Naboo   Human

[87 rows x 8 columns]

### 2) ¿Cómo eliminar duplicados?

In [6]:
d_star_wars_2 = d_star_wars[['hair_color',	'skin_color']]

d_star_wars_2

   hair_color   skin_color
0       blond         fair
1         NaN         gold
2         NaN  white, blue
3        none        white
4       brown        light
..        ...          ...
82      brown        light
83      brown        light
84       none         none
85        NaN          NaN
86      brown        light

[87 rows x 2 columns]

In [ ]:
d_star_wars_3=d_star_wars_2.drop_duplicates()

d_star_wars_3

In [ ]:
d_star_wars_3.shape

2.b) ¿Cómo obtener los registros duplicados?

In [ ]:
d_star_wars_2[d_star_wars_2.duplicated()]

In [ ]:
d_star_wars_2[d_star_wars_2.duplicated()].shape

### 3) ¿Cómo ordenar un data frame?

In [ ]:
d_star_wars.sort_values('birth_year') # analizar los últimos valores...

In [ ]:
# Orden descendente
d_star_wars.sort_values('birth_year', ascending=False)

In [ ]:
from google.colab.data_table import DataTable

# Ordenar por dos columnas
DataTable(d_star_wars.sort_values(['species', 'birth_year']))

In [ ]:
# Emprolijar para chequear
d_sw_ordenado=d_star_wars.sort_values(['species', 'birth_year'])

In [ ]:
# Comprobamos que están ordenados
d_sw_ordenado=d_sw_ordenado[['species', 'birth_year']]

DataTable(d_sw_ordenado)

### 4) ¿Cómo crear una variable en un dataframe?

In [ ]:
d_star_wars['nueva_variable']=999

d_star_wars

In [ ]:
# Pasando a metros la altura
d_star_wars['height_mts']=d_star_wars['height']/100

d_star_wars.head()

### 5) ¿Cómo reordenar variables en un pandas data frame?

In [ ]:
# Tomo las 3 priemras columnas (name, height, mass)
d_star_wars_4=d_star_wars.iloc[:, 0:3]
d_star_wars_4.columns

In [ ]:
# reorden
d_star_wars_5=d_star_wars_4[['mass', 'height', 'name']]

In [ ]:
d_star_wars_5

### 6) ¿Cómo renombrar variables?

In [ ]:
d_star_wars_5.head()

In [ ]:
d_star_wars_5.rename(columns={'mass':'peso', 'height':'altura', 'name':'nombre'}).head()

In [ ]:
# Aplicar función a todas las columnas. Todo a minúscula o mayúscula

d_star_wars_5.rename(str.upper, axis="columns").head()

Eliminar espacios de las columnas

In [ ]:
d_star_wars_6=d_star_wars_5.rename(columns={'mass':'peso del personaje', 'height':'altura del personaje'})
d_star_wars_6.head()

In [ ]:
d_star_wars_6.columns = d_star_wars_6.columns.str.replace(' ', '_')

d_star_wars_6.head()

### 7)  ¿Cómo filtrar datos con pandas query?

In [ ]:
d_star_wars.query(" height > 220 ")

In [ ]:
# AND
d_star_wars.query(" height > 220 and hair_color == 'brown' ")

In [ ]:
# OR, filtrar extremos
d_star_wars.query("height < 150 or height > 220 ")

### 8) Descripción estadística básica

In [ ]:
#Instalamos funpymodeling para obtener estadística de los datos

%%capture
!pip install funpymodeling

In [ ]:
#importamos la librería para poder utilizarla
from funpymodeling.exploratory import status, freq_tbl, profiling_num

In [ ]:
# Análisis univariado var numérica
profiling_num(d_star_wars)

In [ ]:
profiling_num(d_star_wars['birth_year'])

In [ ]:
# Análisis univariado var categórica
freq_tbl(d_star_wars)

¿Cómo aplicar funciones de sumarización a cada columna?

In [ ]:
d_star_wars['height'].max()

In [ ]:
d_star_wars['height'].mean()

In [ ]:
print("El promedio de altura es %s y el  de la altura en mts es: %s" % (str(d_star_wars['height'].mean()), str(d_star_wars['height_mts'].mean())))

### 9) ¿Cómo exportar un pandas dataframe a csv?
(y directorio de trabajo)

In [ ]:
d_star_wars_2.head()

In [ ]:
#Creamos un archivo csv desde un dataframa
d_star_wars_2.to_csv('starwars_colab.csv',  sep=',', index=False)

In [ ]:
#Bajamos el archivo
files.download('starwars_colab.csv')

#Ejercicios

Ejercicio 1: Basado en el dataframe d_star_wars agregar una columna nueva llamada BMI y calcular el indice de masa corporal (BMI) de cada personaje (mostrar nombre y BMI) [BMI = weight (kg) / height² (m²)]

In [8]:
#Antes de comenzar con los ejercicios volvemos a cargar los datos
d_star_wars = pd.read_csv(filepath_or_buffer="https://raw.githubusercontent.com/fpineyro/homework-0/master/starwars.csv", sep=',')

#Convertimos la columna peso (mass) a valores decimales
d_star_wars['mass'] = pd.to_numeric(d_star_wars['mass'], errors='coerce')

d_star_wars

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,species
0,Luke Skywalker,172.0,77.0,blond,fair,blue,19BBY,male,Tatooine,Human
1,C-3PO,167.0,75.0,NaN,gold,yellow,112BBY,NaN,Tatooine,Droid
2,R2-D2,96.0,32.0,NaN,"white, blue",red,33BBY,NaN,Naboo,Droid
3,Darth Vader,202.0,136.0,none,white,yellow,41.9BBY,male,Tatooine,Human
4,Leia Organa,150.0,49.0,brown,light,brown,19BBY,female,Alderaan,Human
...,...,...,...,...,...,...,...,...,...,...
82,Rey,NaN,NaN,brown,light,hazel,NaN,female,NaN,Human
83,Poe Dameron,NaN,NaN,brown,light,brown,NaN,male,NaN,Human
84,BB8,NaN,NaN,none,none,black,NaN,none,NaN,Droid
85,Captain Phasma,NaN,NaN,NaN,NaN,NaN,NaN,female,NaN,NaN
86,Padmé Amidala,165.0,45.0,brown,light,brown,46BBY,female,Naboo,Human

In [10]:
#Ejercicio 1
d_star_wars['height_mts'] = d_star_wars['height'] / 100
d_star_wars['BMI'] = d_star_wars['mass'] / (d_star_wars['height_mts'] * d_star_wars['height_mts'])
d_star_wars[['name', 'BMI']]

              name        BMI
0   Luke Skywalker  26.027582
1            C-3PO  26.892323
2            R2-D2  34.722222
3      Darth Vader  33.330066
4      Leia Organa  21.777778
..             ...        ...
82             Rey        NaN
83     Poe Dameron        NaN
84             BB8        NaN
85  Captain Phasma        NaN
86   Padmé Amidala  16.528926

[87 rows x 2 columns]

Ejercicio 2: Mostrar nombre, altura y peso de todos los personajes ordenardos de mayor altura a menor altura

In [12]:
#Ejercicio 2
d_star_wars.sort_values('height', ascending=False)[['name', 'height', 'mass']]

              name  height   mass
53     Yarael Poof   264.0    NaN
77         Tarfful   234.0  136.0
68         Lama Su   229.0   88.0
12       Chewbacca   228.0  112.0
34    Roos Tarpals   224.0   82.0
..             ...     ...    ...
81            Finn     NaN    NaN
82             Rey     NaN    NaN
83     Poe Dameron     NaN    NaN
84             BB8     NaN    NaN
85  Captain Phasma     NaN    NaN

[87 rows x 3 columns]

Ejercicio 3: Del campo hair_color reemplazar los valores nulos por 0 (cero)

In [13]:
#Ejercicio 3

d_star_wars['hair_color'].fillna(0, inplace=True)
d_star_wars

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,species,height_mts,BMI
0,Luke Skywalker,172.0,77.0,blond,fair,blue,19BBY,male,Tatooine,Human,1.72,26.027582
1,C-3PO,167.0,75.0,0,gold,yellow,112BBY,NaN,Tatooine,Droid,1.67,26.892323
2,R2-D2,96.0,32.0,0,"white, blue",red,33BBY,NaN,Naboo,Droid,0.96,34.722222
3,Darth Vader,202.0,136.0,none,white,yellow,41.9BBY,male,Tatooine,Human,2.02,33.330066
4,Leia Organa,150.0,49.0,brown,light,brown,19BBY,female,Alderaan,Human,1.50,21.777778
...,...,...,...,...,...,...,...,...,...,...,...,...
82,Rey,NaN,NaN,brown,light,hazel,NaN,female,NaN,Human,NaN,NaN
83,Poe Dameron,NaN,NaN,brown,light,brown,NaN,male,NaN,Human,NaN,NaN
84,BB8,NaN,NaN,none,none,black,NaN,none,NaN,Droid,NaN,NaN
85,Captain Phasma,NaN,NaN,0,NaN,NaN,NaN,female,NaN,NaN,NaN,NaN
86,Padmé Amidala,165.0,45.0,brown,light,brown,46BBY,female,Naboo,Human,1.65,16.528926

Ejercicio 4: Listar los personajes femeninos de la raza humana.

In [14]:
#Ejercicio 4
d_star_wars.query("gender == 'female' and species == 'Human'")

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,species,height_mts,BMI
4,Leia Organa,150.0,49.0,brown,light,brown,19BBY,female,Alderaan,Human,1.50,21.777778
6,Beru Whitesun lars,165.0,75.0,brown,light,blue,47BBY,female,Tatooine,Human,1.65,27.548209
26,Mon Mothma,150.0,NaN,auburn,fair,blue,48BBY,female,Chandrila,Human,1.50,NaN
40,Shmi Skywalker,163.0,NaN,black,fair,brown,72BBY,female,Tatooine,Human,1.63,NaN
57,Cordé,157.0,NaN,brown,light,brown,NaN,female,Naboo,Human,1.57,NaN
62,Dormé,165.0,NaN,brown,light,brown,NaN,female,Naboo,Human,1.65,NaN
70,Jocasta Nu,167.0,NaN,white,fair,blue,NaN,female,Coruscant,Human,1.67,NaN
82,Rey,NaN,NaN,brown,light,hazel,NaN,female,NaN,Human,NaN,NaN
86,Padmé Amidala,165.0,45.0,brown,light,brown,46BBY,female,Naboo,Human,1.65,16.528926

Ejercicio 5: listar todos los personajes que miden más de 2 metros.

In [15]:
#Ejercicio 5
d_star_wars.query("height>200")

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,species,height_mts,BMI
3,Darth Vader,202.0,136.0,none,white,yellow,41.9BBY,male,Tatooine,Human,2.02,33.330066
12,Chewbacca,228.0,112.0,brown,NaN,blue,200BBY,male,Kashyyyk,Wookiee,2.28,21.545091
34,Roos Tarpals,224.0,82.0,none,grey,orange,NaN,male,Naboo,Gungan,2.24,16.342474
35,Rugor Nass,206.0,NaN,none,green,orange,NaN,male,Naboo,Gungan,2.06,NaN
53,Yarael Poof,264.0,NaN,none,white,yellow,NaN,male,Quermia,Quermian,2.64,NaN
68,Lama Su,229.0,88.0,none,grey,black,NaN,male,Kamino,Kaminoan,2.29,16.780763
69,Taun We,213.0,NaN,none,grey,black,NaN,female,Kamino,Kaminoan,2.13,NaN
76,Grievous,216.0,159.0,none,"brown, white","green, yellow",NaN,male,Kalee,Kaleesh,2.16,34.079218
77,Tarfful,234.0,136.0,brown,brown,blue,NaN,male,Kashyyyk,Wookiee,2.34,24.837461
80,Tion Medon,206.0,80.0,none,grey,black,NaN,male,Utapau,Pau'an,2.06,18.851918

Ejercicio 6: calcular el peso promedio de los personajes por género. Redondear el peso a dos decimales.

In [16]:
#Ejercicio 6

d_star_wars.groupby('gender')['mass'].mean().round(2)

gender
female            54.02
hermaphrodite       NaN
male              81.00
none             140.00
Name: mass, dtype: float64

Ejercicio 7: Calcular la altura máxima por cada especie

In [18]:
#Ejercicio 7

d_star_wars.groupby('species')['height'].max()

species
Aleena             79.0
Besalisk          198.0
Cerean            198.0
Chagrian          196.0
Clawdite          168.0
Droid             200.0
Dug               112.0
Ewok               88.0
Geonosian         183.0
Gungan            224.0
Human             202.0
Hutt              175.0
Iktotchi          188.0
Kaleesh           216.0
Kaminoan          229.0
Kel Dor           188.0
Mirialan          170.0
Mon Calamari      180.0
Muun              191.0
Nautolan          196.0
Neimodian         191.0
Pau'an            206.0
Quermian          264.0
Rodian            173.0
Skakoan           193.0
Sullustan         160.0
Tholothian        184.0
Togruta           178.0
Toong             163.0
Toydarian         137.0
Trandoshan        190.0
Twi'lek           180.0
Vulptereen         94.0
Wookiee           234.0
Xexto             122.0
Yoda's species     66.0
Zabrak            175.0
Name: height, dtype: float64

Ejercicio 8: Calcular la cantidad de personajes que contienen ojos de color rojo

In [21]:
#Ejercicio 8
d_star_wars.query("eye_color == 'red'").shape[0]

5

Ejercicio 9: Mostrar los personajes que son del planeta Kamino y tienen piel de color gris

In [26]:
#Ejercicio 9
d_star_wars.query("homeworld == 'Kamino' and skin_color == 'gray'")

Empty DataFrame
Columns: [name, height, mass, hair_color, skin_color, eye_color, birth_year, gender, homeworld, species, height_mts, BMI]
Index: []

Ejercicio 10: Mostrar los personajes que midan menos de 1 metro y que sean hombres

In [31]:
#Ejercicios 10

d_star_wars.query("height < 100 and gender == 'male'")

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,species,height_mts,BMI
18,Yoda,66.0,17.0,white,green,brown,896BBY,male,NaN,Yoda's species,0.66,39.026630
28,Wicket Systri Warrick,88.0,20.0,brown,brown,brown,8BBY,male,Endor,Ewok,0.88,25.826446
44,Dud Bolt,94.0,45.0,none,"blue, grey",yellow,NaN,male,Vulpter,Vulptereen,0.94,50.928022
71,Ratts Tyerell,79.0,15.0,none,"grey, blue",NaN,NaN,male,Aleen Minor,Aleena,0.79,24.034610